#!/usr/bin/env python3

import asyncio
import datetime
import random
import websockets
import wikiquote

import dateutil.parser
import datetime
import time
import json
from rocketchat_API.rocketchat import RocketChat
import subprocess


def main():
    
    rocket = RocketChat(auth_token="XXXXXXXXXXXXXXXXXX", user_id="XXXXXXXXXXXXXXXXXX")

    while True:
        m = subprocess.getoutput("cat /var/local/FH").replace("	", "\\t")
        rocket.chat_post_message(m, channel="XXXXXXXXXXXXXXXXXX")
        time.sleep(1)
    return 1


if __name__ == "__main__":
    main()
